### ISSUE TITLE
Different authors presented in social share links

### ISSUE THREAD

**Issue by mrchrisadams** [climateaction-tech/branch-theme#26]
At present, the open graph plugin listing on a page lists what we might call _wordpress_'s idea of a post author, not the author we are able to specify with our own set your own author plugin.

You can see it in the header text at the link below

https://branch.climateaction.tech/issues/issue-3/beyond-single-dimensional-metrics-for-digital-sustainability/

And the markup generated is here:

```html

	<meta name="twitter:description" content="Have you ever been working towards making a piece of software greener and then you go and check against a tool to see if it made an impact and you end up disappointed?"/>
	<meta name="twitter:image" content="https://branch.climateaction.tech/wp-content/uploads/2021/11/pexels-photo-7318063.jpeg"/>
	<meta name="twitter:label1" content="Written by"/>
	<meta name="twitter:data1" content="Carrie Hou"/>
	<meta name="twitter:label2" content="Estimated reading time"/>
	<meta name="twitter:data2" content="9 minutes"/>
```

This means that it looks like Carrie is the author when these links are shared:
![Screenshot 2021-12-07 at 16 56 47](https://user-images.githubusercontent.com/17906/145062814-8ecc6e4d-baca-424a-b6d2-2d38205c6377.png)

### Where to fix this

I don't know how we can fix this in the app, as there doesn't seem to be an obvious place in the Yoast SEO plugin:

![Screenshot 2021-12-07 at 16 52 11](https://user-images.githubusercontent.com/17906/145061956-f9f1807b-294a-4cf5-9988-a470093da59e.png)
![Screenshot 2021-12-07 at 16 52 21](https://user-images.githubusercontent.com/17906/145061950-4676c25b-db86-473e-985e-ce505de27de5.png)

How do we set the open graph generation to honour our special author override, so we're able to have say… Carrie publish, but then list Abhishek as an author in the right place?

**Comment by jacklenox** [comment]
As above (and thanks to @scottsweb for drawing my attention to it), this has been fixed in Co-Authors Plus, and I've fixed the problem that was preventing us being able to update Co-Authors Plus. The plugin is now up-to-date, and thus this issue is resolved. :raised_hands:
