### ISSUE TITLE
Gif doesn't play in article

### ISSUE THREAD

**Issue by thornet** [climateaction-tech/branch-theme#4]
The gif in this article doesn't "play". I only see a still, rather than multiple frame. When I try to upload another version of the file, I get a "post-processing" error. 

Gif: https://lh3.googleusercontent.com/No_pOnaPakzbRn_fEsi0QhxEvGxVzjW034fo6O7Vdz7ZucU3KFZ1FKynv4iZF8LzFGxaf2F-AFSkRIn0qIPELQPJ0olWxfK_Q1kKByCafSTFIOWGDvSn3t3-dTTSFQVe9_U6KhHL

in this article: https://branch-staging.climateaction.tech/2020/10/11/design-for-carbon-aware-digital-experiences/

**Comment by jacklenox** [comment]
This is a kind-of feature of WordPress! In order to show the actual gif, it needs to be added at "full size": https://www.greengeeks.com/tutorials/article/how-to-add-gif-images-in-wordpress/

**Comment by jacklenox** [comment]
I see you got this working by linking to the original.
