### ISSUE TITLE
Center Google Slides

### ISSUE THREAD

**Issue by thornet** [climateaction-tech/branch-theme#5]
In this article, would it be possible to align-center the slides? I unfortunately don't have that option in the block editor. 

https://branch-staging.climateaction.tech/2020/10/05/seeing-black-and-green-in-tech/

**Comment by jacklenox** [comment]
This appears to be centred to me.

![Screenshot_2020-10-27 Seeing Black and Green in Tech - Branch](https://user-images.githubusercontent.com/751476/97283732-1c7b2600-1838-11eb-92e4-15657e77f81f.png)

**Comment by hanopcan** [comment]
Just checked in on this and from what I can see the google slides are centered. Certainly nothing is looking broken so I'm going to close this off.
