### ISSUE TITLE
Slideshare title automatically pulled + deck small size

### ISSUE THREAD

**Issue by laurence-b** [climateaction-tech/branch-theme#6]
Because the title is pulled automatically, it creates text we don't want, especially on this article, where it repeats the title just above
https://branch-staging.climateaction.tech/2020/10/15/dont-press-snooze-design-in-a-crisis/

Also, it is not possible as editor to control the size of the block. it seems much smaller than any other default top image, any chance to make it a bit bigger?

**Comment by jacklenox** [comment]
I personally don't feel this is too bad, but if the feeling is strong I can add some CSS to hide this.

On the second point, I'm not sure where the root width is coming from but I can add an exception to make it bigger. It looks as though the editor doesn't let us control the width of this.

**Comment by hanopcan** [comment]
I'm going to close this issue off. 

I think its important the slides have a title and author beneath, as I don't think in every case they will be duplication of the post's title and author. Nor will they always be at the top of an article.

In terms of the width, in an ideal world they might be nice slightly wider. However, there is a full width option in the bottom right of the slides so someone who wants to see a larger version of the slides can.
