### ISSUE TITLE
3- massive gaps in pull quote

### ISSUE THREAD

**Issue by laurence-b** [climateaction-tech/branch-theme#7]
we are using pullquotes to highlight interesting quotes in the article.
i am not sure whether it is due to us not using 'citation' (i.e. an extra line of text to say whose the author) but pullquotes have massive gaps above and below them
see https://branch-staging.climateaction.tech/2020/10/15/dont-press-snooze-design-in-a-crisis/

Confirming it is because of citation. I am not sure it works very well in terms of design, when you add the citation, because it is exactly the same font type and size as the main text, it doesn't look like a citation, see https://branch-staging.climateaction.tech/2020/10/15/one-vision-one-world-whose-world-then/

**Comment by laurence-b** [comment]
ps: i think on this particular article Michelle might want to make less liberal a use of pull quotes anyway ;)

**Comment by thornet** [comment]
Revised that article! It looks better now.

**Comment by jacklenox** [comment]
Just to check I haven't accidentally fixed this, do we think these are massive gaps?

![Screenshot_2020-10-27 Don’t Press Snooze Design in a Crisis - Branch](https://user-images.githubusercontent.com/751476/97282842-120c5c80-1837-11eb-9d2b-598199d3056e.png)

I don't mind the white space but maybe it's a bit too much. I'll check with Tom.

**Comment by hanopcan** [comment]
I'm going to close this issue. The white space we can currently see around pullquotes is spacious, but isn't broken.
