### ISSUE TITLE
2- cutting words in two

### ISSUE THREAD

**Issue by laurence-b** [climateaction-tech/branch-theme#8]
see the biog, project on my smallish macbok screen is spelt projec
t.
i can confirm this is not how it is written in the text.

https://branch-staging.climateaction.tech/2020/09/29/the-right-to-repair/

<img width="1280" alt="Screenshot 2020-10-18 at 18 05 12" src="https://user-images.githubusercontent.com/73073369/96374754-8d517c80-116c-11eb-8e6e-f55dc3fac590.png">

**Comment by laurence-b** [comment]
same here https://branch-staging.climateaction.tech/2020/10/10/hands-on-sustainable-web-design/

**Comment by thornet** [comment]
Yes, @jacklenox there is still the issue of links having strange linebreaks.

**Comment by laurence-b** [comment]
tested and it is solved
