### ISSUE TITLE
page not found from contents

### ISSUE THREAD

**Issue by laurence-b** [climateaction-tech/branch-theme#9]
https://branch-staging.climateaction.tech/2020/10/13/if-i-am-a-techie-how-can-i-help-solve-climate-change/
is now https://branch-staging.climateaction.tech/2020/10/14/if-i-am-a-techie-how-can-i-help-solve-climate-change/

but the contents page still has the old slug, see https://branch-staging.climateaction.tech/

**Comment by thornet** [comment]
I;ve updated that. Thanks!
